name: "app-nagios-nrpe"
version: "1.0.0"
slug: folder
description: >-
  "Home Assistant App for NRPE Server for Nafios Plugins"
arch:
  - amd64
  - aarch64
url: "https://github.com/petrivirkkula/hassio-app-nagios-nrpe"
ports:
  5666/tcp: 5666
ports_description:
  5666/tcp: Nagios NRPE default port
host_network: true
#apparmor: true
image: ghcr.io/petrivirkkula/hassio-app-nagios-nrpe
options:
  allowed_hosts: "127.0.0.1"
schema:
  allowed_hosts: str?
